import type { Metadata } from "next";
import { Nunito_Sans } from "next/font/google";
import { Poppins } from "next/font/google";

import "@/styles/globals.css";

import Nav from "@/components/Nav";

export const metadata: Metadata = {
  title: "ScholaFlow",
  description: "Generated by create next app",
};

const nunitoSans = Nunito_Sans({ subsets: ["latin"], display: "swap" });
const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export interface FontType {
  className: string;
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} box-border bg-[#edf2ff] text-[#33383d] antialiased`}
      >
        <Nav font={nunitoSans} />
        {children}
      </body>
    </html>
  );
}
